# Generated by Django 4.2.1 on 2023-06-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0003_alter_employee_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("device_company_name", models.CharField(max_length=255)),
                ("device_type", models.CharField(max_length=255)),
                ("device_model", models.CharField(max_length=255)),
                ("device_info", models.CharField(max_length=255)),
                (
                    "device_assigned_from",
                    models.DateTimeField(blank=True, default=None),
                ),
                ("device_assigned_to", models.DateTimeField(blank=True, default=None)),
                ("device_log", models.CharField(max_length=255)),
                (
                    "device_currently_used",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "device_returned",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "device_returned_date",
                    models.DateTimeField(blank=True, default=None),
                ),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
