# Generated by Django 4.2.1 on 2023-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_currently_used",
            field=models.CharField(choices=[("1", "Yes"), ("0", "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_returned",
            field=models.CharField(choices=[("1", "Yes"), ("0", "No")], max_length=3),
        ),
    ]
