# Generated by Django 4.2.1 on 2023-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_device_currently_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_assigned_from",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_assigned_to",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_currently_used",
            field=models.CharField(choices=[("1", "Yes"), ("2", "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_returned",
            field=models.CharField(choices=[("1", "Yes"), ("2", "No")], max_length=3),
        ),
    ]
