# Generated by Django 4.2.1 on 2023-06-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
