# Generated by Django 4.2.1 on 2023-06-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Company Email"
            ),
        ),
    ]
